name: Deploy Frontend to Render

on:
  push:
    branches: [main]

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy Frontend Service to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          FRONTEND_SERVICE_ID: ${{ secrets.FRONTEND_SERVICE_ID }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Accept: application/json" \
            "https://api.render.com/v1/services/$FRONTEND_SERVICE_ID/deploys"
